import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"], 
  weight: ["400", "500", "700"], // Defina os pesos desejados
  variable: "--font-roboto", // Nome da variável CSS
});

export const metadata = {
  title: "Codex Academy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
